import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import { EventStoreProvider } from "@/lib/data/event-store";
import { PLATFORM_NAME, PLATFORM_TAGLINE } from "@/lib/constants";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const siteUrl =
  process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: PLATFORM_NAME,
    template: `%s · ${PLATFORM_NAME}`,
  },
  description: PLATFORM_TAGLINE,
  applicationName: PLATFORM_NAME,
  keywords: [
    "civic intelligence",
    "road safety analytics",
    "municipal dashboard",
    "CCTV analytics",
    "open source",
    "India",
    "smart city",
  ],
  authors: [{ name: "Civic AI Platform Contributors" }],
  openGraph: {
    type: "website",
    locale: "en_IN",
    siteName: PLATFORM_NAME,
    title: PLATFORM_NAME,
    description: PLATFORM_TAGLINE,
    // Generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: PLATFORM_NAME,
    description: PLATFORM_TAGLINE,
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider>
          <EventStoreProvider>
            {children}
            <Toaster richColors position="top-right" />
          </EventStoreProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
